default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: kXO6RF3r
  host: mysql-157616-0.cloudclusters.net
  port: 18415

development:
  <<: *default
  database: Volunteer_Student_Management
